language: cpp
compiler: gcc

os: linux
addons:
  apt:
    packages:
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CONFIGURATION_TYPES="Debug;Release"
  - cmake --build . --config Release