@startuml
title Core package \n [[level3.html <&arrow-top> Уровень 3]]
package "Core" {
class LoggerModel {
  startWrite()
  stopWrite()
}
LoggerModel "1" --> "3" IDataProvider: содержит
LoggerModel "1" --> "1" ILogWriter: содержит
}
package "dataproviders" {
IDataProvider <|-- StubDataProvider 
IDataProvider <|-- M8DataProvider 
M8Driver *- M8DataProvider
}
package "logwriters" {
ILogWriter <|-- CsvLogWriter 
ILogWriter <|-- TxtLogWriter 
}
@enduml